SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE t_note
(
	NOTE_ID int NOT NULL AUTO_INCREMENT COMMENT 'ノートID',
	USR_ID int NOT NULL COMMENT 'ユーザID',
	TITLE text NOT NULL COMMENT 'タイトル',
	CONTENT text NOT NULL COMMENT 'コンテンツ',
	PUBLIC varchar(20) COMMENT 'PUBLIC',
	STATUS int NOT NULL COMMENT 'ステータス',
	INSERT_DATE datetime NOT NULL COMMENT '登録日',
	UPDATE_DATE datetime NOT NULL COMMENT '更新日',
	PRIMARY KEY (NOTE_ID)
) COMMENT = 'ノート' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;



